### ISSUE TITLE
Address books are showing up as Calendars when adding CalDAV

### ISSUE THREAD

**Issue by ioogithub** [etesync/etesync-dav#101]
When adding a new calendar (CalDAV), the user is shown two Default entries. One entry is "Default Contact, Events, Memoes, Tasks" the other is "Default Events"

"Default events" i the calendar while "Default Contact, Events, Memoes, Tasks" is the Address book.

The user however can select the Address book as the calendar. When events are created, they will not be synced properly.

**Comment by tasn** [comment]
Thanks for reporting!

Note to self: we already talked over mail, and I sent him a version to test though it didn't fix it.

**Comment by tasn** [comment]
I just tested again with TbSync for Thunderbird and it's detected correctly. It kind of smells like an Evolution bug to be honest.

Does it happen to you when adding address books too? That is, do you see calendars there?

**Comment by ioogithub** [comment]
It could be but what caught my attention is that I was never presented with two options in all of the previous testing. 

This time I saw two selection and I was mislead because they both have "events" in the description so choosing the wrong one lead me down the wrong path.

In the address book I only see "Default Contact, Events, Memoes, Tasks but I assumed that Events was a Calendar function.

Perhaps the descriptions could be changed to make it more clear?

**Comment by tasn** [comment]
Events are calendars. The problem here is that for some reason Evolution thinks that the Address Book supports all of those things. Which it doesn't.
TbSync detects it correctly, so I'm inclined to believe it's an issue with Evolution, but I'm not sure. Could you maybe try to open a ticket with Evolution? If I can chat to one of the evolution devs I'm sure we can figure this out in minutes.

We unfortunately don't control the description, it's evolution that does it. It just shows what it thinks it detected from etesync-dav. The description will be correct once they don't mis-detect (or us misrepresent) the address book as a calendar.

**Comment by tasn** [comment]
Oops, I forgot to mention it. I fixed it in 088a68275b385df25e768998d92015c42abb18f7.
