### ISSUE TITLE
docker run for every time etesync-dav is started.

### ISSUE THREAD

**Issue by Nouwan** [etesync/etesync-dav#111]
Recently I installed etesync-dav in a docker container on my system. The instructions say the following:
![image](https://user-images.githubusercontent.com/18347384/73311333-7c4f8c80-4226-11ea-9755-78b5505999e3.png)

However if I'm not mistaken run creates a new container. Using this command every time would create a new container on every start. Is there a reason why reusing the container is a bad idea?

**Comment by tasn** [comment]
This command reuses the container, and it shouldn't be run every time. This documentation is wrong and is a relic of how it used to be invoked. More than that, the `--restart=always` part even makes it run automatically on boot and restart on crashes.

Would you like to make a PR fixing the docs (since you found it), or would you rather I did it?

**Comment by Nouwan** [comment]
I will create a PR to correct the documentation this week.

**Comment by tasn** [comment]
Great, looking forward, thanks!

Please make sure to include "Fixes #111" in the commit message.
