### ISSUE TITLE
Encrypted WebDAV

### ISSUE THREAD

**Issue by mcladyz** [etesync/etesync-dav#12]
Please let me know if this is a wrong repo for this question.

Have you considered implementing encrypted WebDAV for files?

**Comment by tasn** [comment]
Hey,

This is not really the right place for questions, the right place would be contacting the devs/support, though since you already opened this ticket, let me reply here.

EteSync is not DAV based. EteSync itself doesn't (yet?) support generic files, so this repo doesn't either.
Has it been considered? Yes. Though there are already other end-to-end encrypted file stores, so EteSync won't provide much value compared to them. So this is probably not a priority, and unlikely to be any time soon.
