### ISSUE TITLE
Is TBSync needed & why?

### ISSUE THREAD

**Issue by zeronymous** [etesync/etesync-dav#152]
Thunderbird supports CalDAV out of the box  Yet the readme says to install TBSync add-on and dav-4-tbsync add-on.  Is it really necessary to install a third-party add-on, and an add-on to that add-on to interact with EteSync-DAV, and if so, why?

**Comment by tasn** [comment]
It's not required, it's just significantly better than the built-in Thunderbird CalDAV support. Not just with etesync-dav, in general.
In the near future we should have a native Thunderbird add-on (more info: https://blog.etesync.com/etesync-thunderbird-add-on/ ) that uses TbSync too.

**Comment by zeronymous** [comment]
I'd like to update the readme with an explanation of why TbSync is needed/recommended, and what needs to be done to use eteSync without it, but but it's still unclear to me.  Can you explain, or at least point me in the right direction?

**Comment by tasn** [comment]
Here is the commit where we started recommending TbSync instead of Lightning: f5caa91191c8d8af51a9fe113b75d843c2a0d07d
From the previous readme version:
```
* Thunderbird
    * CardDAV: Works.
        * Notes: requires the
          [CardBook](https://addons.mozilla.org/en-US/thunderbird/addon/cardbook/)
add-on, path should include the username as above, and vCard version should
be set to v4.0 when prompted
    * CalDAV: Only works when providing full collection path.
        * Requires the
          [Lightning](https://addons.mozilla.org/en-US/thunderbird/addon/lightning/)
```

As you can see, without TbSync you also needed the Cardbook plugin installed for contacts (so you needed another plugin anyway), but also as I said Cardbook and Lightning (the default Thunderbird one) work much worse than TbSync.
The main reason is kind of implied in the above `Only works when providing full collection path.`.
TbSync does automatic collection discover, so it automatically finds all of your calendars/contact lists and let you add whichever you want. This is not the case with Lightning which requires you use the full path to each calendar (that is, add each calendar manually).

**Comment by zeronymous** [comment]
Thanks, that makes sense.  
What's the convention for collection paths?  If you just had a single calendar you wanted to sync, what would the path look like?

**Comment by tasn** [comment]
You need to use the paths from `http://localhost:37358`. Click on your username and then copy the path for each calendar from there.
It's not something you can guess because it relies on the unique identifier of each calendar which is randomly generated.

**Comment by zeronymous** [comment]
oh jeez.  I didn't realize that clicking on the username lead to an information page - just dismissed it as a mailto: link, lol.  
Thanks, that's really helpful.
