### ISSUE TITLE
Any one got this working on Debian 9 am64 ?

### ISSUE THREAD

**Issue by lachlanA** [etesync/etesync-dav#172]
Hi,   I tried the debian package install with no luck came up with a lot of dept errors.
The I tried compiling  with no luck,   rust came up with pages of errors,  to many to post here.
But I think this is the core.. problem..  thou    I could be way of base, as there so many pages to look thou.

 error: environment variable `OUT_DIR` not defined
    --> src/lib.rs:62:18
     |
  62 | include!(concat!(env!("OUT_DIR"), "/glue.rs"));
     |                  ^^^^^^^^^^^^^^^
     |
     = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

**Comment by tasn** [comment]
Hey, you got the wrong repo... For the legacy rust library the correct repo is https://github.com/etesync/etebase-rs and for EteSync 2.0 it's https://github.com/etesync/libetebase

The problem you are facing is most likely because Debian ships with an ancient Rust version. You may want to consider using https://rustup.rs/

Come and join us at https://www.etesync.com/community-chat/ and we can help you building the module.
