### ISSUE TITLE
Add a large notice about needing to copy the new DAV specific password

### ISSUE THREAD

**Issue by tasn** [etesync/etesync-dav#174]
Too many users are forgetting about this step and is a source of endless reports.

**Comment by voidplayer** [comment]
Well, i was bout to open a bug before i read this and looked for it, so good idea :D

Also, maybe update the captures of how to configure thunderbird. They have change it in the last version of ubuntu. It took me almost an hour of searching until i found it :(

Also, kontact guide is not working either. Some of the repos are 404 (Or lets wait until it lands on the latest version :)

**Comment by tasn** [comment]
What version of etesync-dav are you using? It should already be much much better.

> Also, maybe update the captures of how to configure thunderbird. They have change it in the last version of ubuntu. It took me almost an hour of searching until i found it :(

Got more information? We would love to fix what's wrong.

> Also, kontact guide is not working either. Some of the repos are 404 (Or lets wait until it lands on the latest version :)

I'll get the links up to date. They are for etesync v1, and indeed, the module has now been updated to etesync 2.0.

**Comment by voidplayer** [comment]
Running etesync-dav in a console could output something like

    open the management UI in your browser: http://localhost:37358/

> What version of etesync-dav are you using? It should already be much much better.

Latest. Theres a button to copy the password. I think that problem was ```Copy the DAV specific password by click the "Copy Password" button next to your newly added username.``` is the last step of making etesync-dav work. It took me very long to have the next step ready where i had to "paste it". 

The wording made me think it was the password i had on the previous step, aka setting a etesync account. It does not mention is a second password etesync-dav specific. Also, i had to be logged in to see the copy password button, which i was not

> Got more information? We would love to fix what's wrong.

This is latest ubuntu. Menus are different (1) and i couldnt follow the instructions. I finally found the account manager double clicking (2)

![image](https://user-images.githubusercontent.com/4019910/98850372-fae38680-2454-11eb-963b-352433fb9b31.png)
