### ISSUE TITLE
Move config to where new Radicale versions won't complain

### ISSUE THREAD

**Issue by LogicalDash** [etesync/etesync-dav#2]
etesync-dav currently keeps its configuration in the same file as Radicale, which is fine in Radicale version 2.0.0 but causes an error in later versions.

**Comment by tasn** [comment]
Are you sure that's correct? Could you please paste the error message? I wrote the module based on radicale 2.0.0 where they recommended putting the config in the same place.

**Comment by tasn** [comment]
Oh, I see you posted it in the other ticket, I'll have to check it out. Annoying that they changed it.

The output:

    ERROR: Invalid configuration: Invalid section 'etesync_storage' in config

**Comment by tasn** [comment]
I tried looking into it, but wasn't able to understand what I'm expected to do. In the meanwhile I reported it to upstream.

I'm seriously considering just hardcoding the values for now, though it sucks because the plugin is meant to be standalone from this wrapper.

Issue upstream: https://github.com/Kozea/Radicale/issues/658
