### ISSUE TITLE
Was WebDAV the right choice?

### ISSUE THREAD

**Issue by bam80** [etesync/etesync-dav#4]
Dear developers,
have you heard of Open Whisper Systems' discontinued Flock project?
It's author claims that the main reason of discontinuity was that [WebDAV was the wrong choice](https://gist.github.com/rhodey/873ae9d527d8d2a38213#webdav-was-the-wrong-choice):
>Choosing the wrong protocol led to unreasonable server costs, at this time Flock is nowhere near affordable.

Instead, following protocols suggested for future projects:
- [Remote Storage](https://remotestorage.io/)
- [JMAP](http://jmap.io/)

How EteSync relates with Flock, and what do you think about it?

**Comment by tasn** [comment]
Heya,

Thanks for your concern. I'm familiar with this blog post and with Flock.

Let me reassure you though. EteSync is **not** based on WebDAV. EteSync uses a custom protocol (server side implementation here: https://github.com/etesync/journal-manager) that does not suffer from the same issues Flock was suffering.

EteSync had to use a custom protocol because of the different approach of having an encrypted change journal rather than encrypted DAV objects. The protocol is very simple and based on current and projected usage levels (people have imported in full address books, calendars and have been using it for a while, myself included) it won't be a problem.

Just to clarify, this repo is for a proxy between Cal/CardDAV and the EteSync server. Such a proxy is needed so applications that don't support EteSync natively, but do support DAV such as thunderbird will work with EteSync without further effort.

I hope this clarifies things.
