### ISSUE TITLE
Documentation incomplete?

### ISSUE THREAD

**Issue by ajvsol** [etesync/etesync-dav#43]
Trying to setup now, can't seem to be able to use `etesync-dav-manage`.

I did the first three commands for setup:
```
pip install etesync-dav
sudo docker run -it --rm -v etesync:/data etesync/etesync-dav setup
sudo docker run --name etesync-dav -d -v etesync:/data -p 37358:37358 --restart=always etesync/etesync-dav
```

Then trying to use `etesync-dav-manage` to create a user, but it says "command not found".

**Comment by tasn** [comment]
What platform are you on?

Also, the pip method and the docker method are two different ones, you don't need to do both...

I'm closing it, as it's a question, rather than a bug report, but feel free to contact support / join IRC for more help. This reminds me that we really need to set up a mailing list...

**Comment by storyjesse** [comment]
Hi tasn thanks heaps for your work on etesync.

How do we contact support / join IRC??

I have never heard of pip or docker. I'm running Linux Mint 18.2 Sonya and neither seem to be installed by default.
I like writing documentation, if you can teach me how to install and get this working then I'll gladly write documentation to help other Luddites like me  get it setup. Even the Setup Guide on https://www.etesync.com/user-guide/ starts by saying "This is the main screen of the application."... What application?
Where do I get this application?
The picture looks like an Android application, so I assume it's an app that I need to install. But where from? Is it on Googleplay? is it on F-Droid? I haven't looked yet just pointing out that I have to use my brains and problem-solve to even start using it ;-)

Please understand I'm not at all trying to rant just trying to be clear :-) And please forgive me posting here but I'm fairly inexperienced on github and don't know how to contact you otherwise.

Cheers
Jesse

**Comment by tasn** [comment]
Hey,

I see you also reached out on email, so we'll continue there, just giving a few answers for posterity.

IRC: instructions + a link to a web chat is available from the about page https://www.etesync.com/about/
User guide: Android app. It was written when there was only an Android app, so I guess it could be a bit ambiguous nowadays, though the images are from the Android app.
Links to the app: top of the main page to both Google play and f-droid.

Hope this clarifies things.

--
Tom
