### ISSUE TITLE
radicale.conf without "\" before whitespace

### ISSUE THREAD

**Issue by zagatta-sonah** [etesync/etesync-dav#53]
Mojave 10.14.3 (18D109)

instead of 
``ssl = yes
    certificate = /Users/USERNAME/Library/Application\ Support/etesync-dav/etesync.crt
    key = /Users/USERNAME/Library/Application\ Support/etesync-dav/etesync.key``

i had to enter 
``ssl = yes
    certificate = /Users/USERNAME/Library/Application Support/etesync-dav/etesync.crt
    key = /Users/USERNAME/Library/Application Support/etesync-dav/etesync.key``

**Comment by porg** [comment]
I can confirm this.

The readme currently has two false informations:
1) Automatic SSL setup via the command `etesync-dav-certgen --trust-cert` is not working in the context of the single executable (like other commands too, see #55)
I tried to rephrase as `etesync-dav certgen --trust-cert` or `etesync-dav --certgen` or `etesync-dav --trust-cert` or `etesync-dav --certgen --trust-cert` but none of this worked.
2) Therefore I followed "Manual SSL setup"
But there the stated file paths with the backslash for whitespace preservation fail with
`[Errno 2] No such file or directory: '/Users/yourUsernameHere/Library/Application\\ Support/etesync-dav/etesync.crt'` which indicates that the backslash itself gets escaped.
Also encapsulating the whole filepath in quotes failed. The Radicale config file seems to take file paths with whitespace.
Another question: Why do all file paths need to be absolute (starting with "/Users/USERNAME/Library/…") instead of just relative path with the tilde prefix "~/Library/…"

**Comment by tasn** [comment]
Thanks for reporting, the instructions are now fixed.

@porg: I know that etesync-dav-certgen doesn't work in the context of the single executable. It was never claimed otherwise. Though I agree it should be fixed. Could you please open a new ticket for that?

As for your question about absolute paths: Radicale used to not support it if memory serves, but I just tested and it works, so I just updated the README accordingly.

I also just pushed a fix for other fields not supporting tilde, though it's unrelated to this one.
