### ISSUE TITLE
Contacts Sync not working (macOS)

### ISSUE THREAD

**Issue by zagatta-sonah** [etesync/etesync-dav#54]
Mac OS Mojave 10.14.3 (18D109)

The Set-Up of the Contact sync works fine. But the Contacts that I have added on my android phone and that are visible via the web interface on my macbook are not getting synched.
The Terminal output is:

`[70000f84b000] WARNING: Client provided invalid sync token '********': Sync token are not supported`

I anonymized the sync token because I am note sure if it is secure to post it here

Calendar Sync works fine

**Comment by tasn** [comment]
The sync token warning is irrelevant (and not a problem), you can safely ignore that.

Web interface being etesync-web, or the web interface of etesync-dav?

I assume you have, because Calendar works, but: have you looked at the specific Mojave installation instructions in the readme? Unfortunately Mojave is buggy and doesn't support using without SSL even when SSL is checked off so there's an extra step involved.

Could you check the readme again and verify you set the correct values?

**Comment by tasn** [comment]
I suspect it's maybe related to #65 which has since been fixed. Could you please try again with v0.7.1?

**Comment by tasn** [comment]
Although this one was created first, #70 has more information, so closing this one as a duplicate.
