### ISSUE TITLE
Using Reverse Proxy will get wrong url.

### ISSUE THREAD

**Issue by HybridGlucose** [etesync/etesync-dav#82]
First there is my nginx conf here:
```
    location /webDAV/ {
        proxy_pass        http://127.0.0.1:37359/;
        proxy_set_header  X-Script-Name /webDAV/;
        proxy_set_header  X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass_header Authorization;
    }
```

Before I update etesync-dav all fine,I guess you change something generate link.
For example my website is https://foo.bar/ and I go to https://foo.bar/webDAV/ will get EteSync DAV Management page right?
There is problem when I login the link will get `/user/username` not `/webDAV/user/username`.
Including `/login/` `/logout/` and `/add/` all have the same problem.

I can't find anywhere to change `BASE_URL` (that I guess effect link).

I setup etesync server and DAV service on the same machine so I need to this.

**Comment by tasn** [comment]
You don't want to expose the management UI to the internet, so continue redirecting 37358 like you did before, that should fix the issue you're facing. If you absolutely must, for some reason, consider just using a subdomain (e.g: https://dav.foo.bar).

As for the underlying issue: unfortunately using the management UI in a subdomain is not supported at the moment. The reason is exactly what I said above: it's not meant to be exposed to the internet.

Hope this helps.

**Comment by HybridGlucose** [comment]
If I using subdomain also have one problem is management UI still give me the link http://localhost:37358/username/SomeSerialNumber/ not https://dav.foo.bar/username/SomeSerialNumber/.
https://github.com/etesync/etesync-dav/blob/fb5f46891b4110e03c32ff3f9f3c78460a6bbfd7/etesync_dav/webui.py#L79
I think `BASE_URL` in this line is a reason.

**Comment by tasn** [comment]
It's definitely the reason, but it's not easy to solve. I guess as a workaround, I could make it load from an environment variable, I guess that would solve it for you?

**Comment by HybridGlucose** [comment]
I think yes, we can get a try.

**Comment by HybridGlucose** [comment]
It works just like old version to redirecting web even using like as First commit I post https://github.com/etesync/etesync-dav/issues/82#issue-476472330.
Thank you.

**Comment by tasn** [comment]
Great to hear!
